### ISSUE TITLE
Починить выделение имен ведущих двойным кликом

### ISSUE THREAD

**Issue by BANOnotIT** [web-standards/podcast#22]
Воспроизведение:
- Открыть https://web-standards.ru/podcast/435/ в Firefox 128.0.3
- Кликнуть два раза на фамилию первого ведущего в списке

Ожидаемый результат:
Выделится фамилия первого ведущего.

Фактический результат:
Выделяется фамилия первого ведущего и имя второго ведущего.

[wstdru-selection.webm](https://github.com/user-attachments/assets/50ec241b-f92b-4c76-8f09-e7267f6fd46f)

Результаты моего исследования:
`.podcast__host {display: inline}` заставляет `<li>` вести себя как `<span>`'ы. А поскольку между элементами списка нет пробела, то они считаются браузером за две части одного слова.
![image](https://github.com/user-attachments/assets/af41001c-3fb7-48a8-a5e0-d9fc7373cd49)

**Comment by pepelsbey** [comment]
Интересно, может быть [`user-select: all`](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) на элементе списка поможет выделять именно его?

**Comment by BANOnotIT** [comment]
Да, `user-select: all` работает, но это не поле ввода с текстом, который нужно скопировать. Я совершенно не уверен, что кто-то будет ожидать выделение всего имени, когда человек, например, хотел только выделить фамилию.

**Comment by pepelsbey** [comment]
Это была гипотеза. Если у вас есть идеи, как это поправить — будем рады пул-реквесту.

**Comment by BANOnotIT** [comment]
У _**Нас**_ есть идеи. Первая идея заключается в том, чтобы сделать запятую с пробелом через nunjuks, а не через `::after { content }`. Но есть опасения, что пробел будет все равно съеден html minifier'ом, так как внутри `<ul>` пробелы до следующего `<li>` вроде как должны быть незначимыми. Пробелы можно эмулировать либо `margin`'ами, либо оставить `::after`. 

Еще одна идея это просто отказаться от семантики `ul>li*` в пользу семантики какого-нибудь RDFa на `<span>`'ах или еще чего-то. Но это прямо обскурная идея.
