### ISSUE TITLE
Ошибка в описаниях эпизодов

### ISSUE THREAD

**Issue by smigles** [web-standards/podcast#4]
В описаниях эпизодов [378](https://github.com/web-standards-ru/podcast/blob/main/src/episodes/378/index.md) и [379](https://github.com/web-standards-ru/podcast/blob/main/src/episodes/379/index.md), в разделе «Ответы на вопросы», есть пункт «HTMLDialogElement: cancel event», хотя в эпизодах в блоке ответов на вопросы об элементе `<dialog>` речь не шла. Этот пункт тянется из описания эпизода [377](https://github.com/web-standards-ru/podcast/blob/main/src/episodes/377/index.md).

**Comment by smigles** [comment]
У эпизода [380](https://github.com/web-standards-ru/podcast/blob/main/src/episodes/380/index.md) аналогично.

@pepelsbey и @MeFoDy, вызываю вас!

**Comment by pepelsbey** [comment]
Спасибо! [Поправили](https://github.com/web-standards-ru/podcast/commit/95f278515b918956328e141b04353972462f8ec3) :)
