### ISSUE TITLE
Найти идеальный формат шоуноутов, который хорошо работает на всех платформах

### ISSUE THREAD

**Issue by pepelsbey** [web-standards/podcast#8]
⚠️ Чтобы приступить к этой задаче, нужно сначала [поменять сборку сайта](https://github.com/web-standards-ru/podcast/issues/7).

Сейчас формат шоуноутов примерно такой:

- Заголовки
- Списки с текстом и ссылками
- Параграфы с текстом и ссылками

```html
<h2>Ведущие</h2>

<p>Никита Дубко, Вадим Макеев, Андрей Мелихов, Алексей Симоненко</p>

<h2>Темы</h2>

<ul>
    <li>00:00:00 Интро</li>
</ul>

<h2>Поддержите нас</h2>

<ul>
    <li><a href="https://www.patreon.com/webstandards_ru">Патреон</a></li>
</ul>

<p><a href="mailto:podcast@web-standards.ru">podcast@web-standards.ru</a></p>
```

Всё это рендерится из маркдауна в фид и на сайт. Для маркдауна и сайта такое очень удобно, но у фида есть проблемы на разных платформах. Например:

YouTube плюс-минус нормально делает плейн-текст, но плохо приклеивает заголовки к предыдущему тексту:

<img width="574" alt="image" src="https://github.com/web-standards-ru/podcast/assets/105274/5c70d288-9e9a-430f-8895-dfffab49906e">

Apple Podcasts тоже дурит с заголовками:

<img width="568" alt="image" src="https://github.com/web-standards-ru/podcast/assets/105274/bfb484a9-71e8-4f2c-99a1-0ed64e2ce90f">

Возможно, нужно вместо заголовков отдавать параграфы. Но кажется, что у Apple проблема даже не с заголовками, а со списками. Похоже, нужно разбираться с каждым случаем.

Самый простой вариант будет сделать плейн-текст. Но может быть плейн-текст со ссылками. Нужно изучить опыт других подкастов, у которых фиды хорошо выглядят.

**Comment by MeFoDy** [comment]
@pepelsbey, а что если сделать копии-фиды под разные источники? Если где-то какой-то баг, сделать отдельный генератор для этой платформы, через поддержку обновить ссылку на фид в источнике. Тогда пользователи будут счастливы, а нам надо не так много работы проделать будет.

Это если не получится универсальное решение найти.

**Comment by pepelsbey** [comment]
> а что если сделать копии-фиды под разные источники?

К сожалению, платформы иногда сами добавляют фиды, которые находят на других платформах или просто в интернете. Особенно это касается популярных подкастов. С дубликатами фидов мы можем столкнуться с тем, что у нас будут дубликаты подкаста на платформе.

Есть одна фишка фидов для подкаста, что там кажется можно отдавать сразу две версии: плейн и рич, чтобы платформа сама выбирала. Это как бывает в почте, кажется.

В любом случает, тут нужен рисёрч и эксперименты. Возможно, есть хорошие статьи на эту тему и официальные руководства платформ или хостеров на эту тему. Но я только читал гайды Apple.
